export { default as Value } from './value.js'
export { default as Integer } from './integer.js'
export { default as BasicBlock } from './basic_block.js'
export { default as Function } from './function.js'
export { default as FunctionArgument } from './function_argument.js'
export * from './function_argument.js'